[package]
name = "grammarconversion"
version = "0.1.0"
authors = ["Altair"]
description = "A converter from a set of grammar rules to json"
edition = "2021"
license = "GPL-3.0"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
regex = "1.11.1"
